networks:
  traefik:
    external: true

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      # Dashboard (unsafe for prod; local only)
      - --api.insecure=true

      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/dynamic/tls.yml
      - --providers.file.watch=true

      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # Logging
      - --log.level=DEBUG

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./dynamic:/dynamic:ro

    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"

      # Dashboard route (HTTPS)
      - "traefik.http.routers.traefik.rule=Host(`admin.traefik.local`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"

      # API route (HTTPS)
      - "traefik.http.routers.traefik-api.rule=Host(`admin.traefik.local`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.entrypoints=websecure"
      - "traefik.http.routers.traefik-api.tls=true"
      - "traefik.http.routers.traefik-api.service=api@internal"

      # HTTP to HTTPS redirect
      - "traefik.http.routers.traefik-redirect.rule=Host(`admin.traefik.local`)"
      - "traefik.http.routers.traefik-redirect.entrypoints=web"
      - "traefik.http.routers.traefik-redirect.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

    networks:
      - traefik

  # Proxy service for your local app running on localhost:3000
  app-proxy:
    image: nginx:alpine
    container_name: app-proxy
    restart: unless-stopped
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # HTTP router: redirect to HTTPS
      - "traefik.http.routers.post-app.rule=Host(`post.adhere.local`)"
      - "traefik.http.routers.post-app.entrypoints=web"
      - "traefik.http.routers.post-app.middlewares=post-app-https-redirect"

      # HTTPS router
      - "traefik.http.routers.post-app-secure.rule=Host(`post.adhere.local`)"
      - "traefik.http.routers.post-app-secure.entrypoints=websecure"
      - "traefik.http.routers.post-app-secure.tls=true"

      # Service configuration - proxy to localhost:3000
      - "traefik.http.services.post-app.loadbalancer.server.port=80"

      # Middleware: HTTP -> HTTPS
      - "traefik.http.middlewares.post-app-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.post-app-https-redirect.redirectscheme.permanent=true"

    networks:
      - traefik
